FROM jenkinsci/ssh-slave

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y git curl \
      lsb-release \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg2 \
      software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) \
       stable" \
    && apt-get update \
    && apt-get install -y docker-ce \
    && rm -rf /var/lib/apt/lists/* \
    && usermod -aG docker jenkins
